# This Dockerfile creates a jupyter lab server that includes all the libraries used at the ECALab, for audit support
# Tested on amd64 (Linux) and armv7 (Raspberry PI 4) architectures. 3h to build on a RPI4
FROM python:3.8
RUN TZ=Europe/Luxembourg ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get -y update
RUN apt-get install -y build-essential python3-dev libssl-dev libcurl4-openssl-dev libspatialindex-dev unixodbc-dev rustc
RUN apt-get install -y libblas-dev gfortran libopenblas-base libatlas-base-dev # For numpy required by gensim
# Create a non-root user
# Please match this with host machine desired uid and gid
RUN groupadd -r --gid 1001 jupyter
RUN useradd --no-log-init --uid 1001 -r -m -g jupyter jupyter
USER jupyter
WORKDIR /home/jupyter
ENV PATH=$PATH:/home/jupyter/.local/bin
# Install packages one by one to take advantage of docker caching
RUN pip3 install --user gensim # numpy, scipy, smart-open, six
RUN pip3 install --user pandas # python-dateutil, pytz
RUN pip3 install --user nltk # tqdm, regex, joblib, click
RUN pip3 install --user spacy # Downgrades smart-open to 3.0.0, installed by gensim, includes urllib3, idna, chardet, certifi, requests, murmurhash, cymem, catalogue, wasabi, typer, srsly, pyparsing, pydantic, preshed, MarkupSafe, blis, thinc, spacy-legacy, pathy, packaging, jinja2
RUN pip3 install --user beautifulsoup4 # soupsieve
RUN pip3 install --user Flask # Werkzeug, itsdangerous
RUN pip3 install --user fuzzywuzzy 
RUN pip3 install --user langid
RUN pip3 install --user lxml
RUN pip3 install --user networkx # decorator
RUN pip3 install --user openpyxl # jdcal, et-xmlfile
RUN pip3 install --user pdfminer.six # pycparser, cffi, sortedcontainers, cryptography
RUN pip3 install --user Pillow
RUN pip3 install --user PyPDF2
RUN pip3 install --user python-docx
RUN pip3 install --user requests
RUN pip3 install --user scikit-learn # threadpoolctl
RUN pip3 install --user SQLAlchemy 
RUN pip3 install --user Unidecode
RUN pip3 install --user XlsxWriter
RUN pip3 install --user camelot-py
RUN pip3 install --user jupyterlab
RUN pip3 install --user matplotlib # kiwisolver, cycler
RUN pip3 install --user seaborn
# Download language model for en
RUN python3 -m spacy download en_core_web_lg
RUN mkdir Notebooks
WORKDIR /home/jupyter/Notebooks
CMD ["jupyter", "lab", "--port=8888", "--no-browser", "--ip=0.0.0.0", "--ServerApp.password='sha1:55803a3a0626:a02e4ebe2e18af4907e8afec9f364bc37c6b5785'"] # password: stocazzo
